[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "fastkaggle"
dynamic = ["version"]
description = "Kaggling for fast kagglers!"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
authors = [{name = "Jeremy Howard", email = "info@fast.ai"}]
keywords = ['machine-learning', 'kaggle', 'fastai', 'nbdev']
classifiers = ["Natural Language :: English", "Intended Audience :: Developers", "Development Status :: 2 - Pre-Alpha", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3 :: Only"]
dependencies = ['fastcore>=1.8', 'kaggle>=2']

[project.urls]
Repository = "https://github.com/fastai/fastkaggle"
Documentation = "https://fastai.github.io/fastkaggle/"

[project.entry-points.nbdev]
fastkaggle = "fastkaggle._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "fastkaggle.__version__"}

[tool.setuptools.packages.find]
include = ["fastkaggle"]

[tool.nbdev]
branch = 'master'
