# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"iskaggle": "00_core.ipynb",
         "import_kaggle": "00_core.ipynb",
         "split_pkgspec": "00_core.ipynb",
         "setup_install": "00_core.ipynb",
         "setup_comp": "00_core.ipynb",
         "nb_meta": "00_core.ipynb",
         "push_notebook": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/fastkaggle/"

git_url = "https://github.com/fastai/fastkaggle/tree/master/"

def custom_doc_links(name): return None
